services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: incognitrix_db_new
      MYSQL_USER: CTF
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=CTF
      - DB_PASSWORD=root
      - DB_NAME=incognitrix_db_new
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./react-website
      dockerfile: Dockerfile
    restart: always
    environment:
      - VITE_BACKEND_URL=http://backend:1337
    ports:
      - "7777:7777"
    depends_on:
      - backend
    volumes:
      - ./react-website:/app
      - /app/node_modules

volumes:
  db_data:
