export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            "colors": {
                "outline-variant": "#414755",
                "tertiary-container": "#ff5545",
                "on-surface-variant": "#c1c6d7",
                "error-container": "#93000a",
                "tertiary": "#ffb4aa",
                "on-primary-fixed-variant": "#004493",
                "secondary-container": "#46464b",
                "inverse-surface": "#e2e2e8",
                "on-secondary-fixed": "#1a1b1f",
                "surface-container-lowest": "#0c0e12",
                "tertiary-fixed": "#ffdad5",
                "on-tertiary-fixed": "#410001",
                "surface-bright": "#37393e",
                "on-background": "#e2e2e8",
                "surface-container": "#1e2024",
                "inverse-on-surface": "#2f3035",
                "tertiary-fixed-dim": "#ffb4aa",
                "surface-dim": "#111317",
                "outline": "#8b90a0",
                "on-secondary-container": "#b5b4ba",
                "on-secondary": "#2f3034",
                "primary-fixed-dim": "#adc6ff",
                "on-error": "#690005",
                "secondary-fixed-dim": "#c6c6cb",
                "on-tertiary-container": "#5c0002",
                "on-tertiary": "#690003",
                "surface-variant": "#333539",
                "on-primary": "#002e69",
                "surface-container-highest": "#333539",
                "on-error-container": "#ffdad6",
                "surface": "#111317",
                "inverse-primary": "#005bc1",
                "surface-tint": "#adc6ff",
                "error": "#ffb4ab",
                "primary-fixed": "#d8e2ff",
                "on-surface": "#e2e2e8",
                "on-tertiary-fixed-variant": "#930005",
                "surface-container-high": "#282a2e",
                "surface-container-low": "#1a1c20",
                "on-secondary-fixed-variant": "#46464b",
                "secondary": "#c6c6cb",
                "on-primary-container": "#00285c",
                "primary-container": "#4b8eff",
                "on-primary-fixed": "#001a41",
                "primary": "#adc6ff",
                "background": "#111317",
                "secondary-fixed": "#e3e2e7"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "fontFamily": {
                "headline": ["Inter", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Space Grotesk", "sans-serif"],
                "mono": ["JetBrains Mono", "monospace"]
            }
        },
    },
    plugins: [],
  }
