/* Designed and engineered by liyander Rishwanth (CyberGhost05) */
import React, { useState, useEffect } from 'react';
function Dashboard({ useDatabase }) {
  const [summary, setSummary] = useState(null);
  const [students, setStudents] = useState([]);
  const [recentAchievements, setRecentAchievements] = useState([]);
  const [recentCves, setRecentCves] = useState([]);
  const [projects, setProjects] = useState([]);
  const [teams, setTeams] = useState([]);
  const [topContributors, setTopContributors] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const apiFetch = (url) => fetch(url, { cache: 'no-store' });

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        if (useDatabase) {
           const [indRes, projRes, achRes, cveRes, teamRes] = await Promise.all([
             apiFetch('/api/individuals'),
             apiFetch('/api/projects'),
             apiFetch('/api/achievements'),
             apiFetch('/api/cves'),
             apiFetch('/api/teams')
           ]);
           if (indRes.ok && projRes.ok && achRes.ok && cveRes.ok && teamRes.ok) {
              const inds = await indRes.json();
              const projs = await projRes.json();
              const achievements = await achRes.json();
              const cves = await cveRes.json();
              const teamRows = await teamRes.json();

              let totalCert = 0;
              const safeInds = Array.isArray(inds) ? inds : [];
              const safeProjects = Array.isArray(projs) ? projs : [];
              const safeAchievements = Array.isArray(achievements) ? achievements : [];
              const safeCves = Array.isArray(cves) ? cves : [];
              const safeTeams = Array.isArray(teamRows) ? teamRows : [];

              const formattedInds = safeInds.map(s => {
                 let achs = [];
                 try { achs = typeof s.achievements === 'string' ? JSON.parse(s.achievements) : s.achievements || []; } catch(e){}
                 totalCert += (achs.length || 0);

                 return {
                   ...s,
                   displayName: s.name,
                   teamName: s.team_name,
                   deptYear: s.year_of_study || s.department,
                   level: s.team_name === 'Technical Team' ? 'Hard' : (s.team_name === 'Internship/Placed' ? 'Expert' : 'Medium'),
                   inferredLevel: s.team_name === 'Technical Team' ? 'Hard' : (s.team_name === 'Internship/Placed' ? 'Expert' : 'Medium'),
                   completedPaths: s.team_name === 'Internship/Placed' ? 2 : 0,
                 };
              });

              setSummary({
                totalStudents: safeInds.length,
                totalCertificates: totalCert,
                activeStudyPaths: safeProjects.length,
                totalAchievements: safeAchievements.length,
                totalCves: 16,
                totalTeams: safeTeams.length
              });

              setStudents(formattedInds);
              setRecentAchievements([...safeAchievements].sort((a, b) => (b.id || 0) - (a.id || 0)).slice(0, 6));
              setRecentCves([...safeCves].sort((a, b) => String(a.cve_number || '').localeCompare(String(b.cve_number || ''))).slice(0, 6));
              setProjects(safeProjects);
              setTeams([...safeTeams].sort((a, b) => {
                if (a.name === 'Red Team') return -1;
                if (b.name === 'Red Team') return 1;
                return String(a.name || '').localeCompare(String(b.name || ''));
              }));

              const contributorCounts = {};
              safeCves.forEach(cve => {
                let contributors = [];
                try { contributors = typeof cve.contributors === 'string' ? JSON.parse(cve.contributors) : cve.contributors || []; } catch(e){}
                contributors.forEach(name => {
                  const key = typeof name === 'string' ? name : name?.name;
                  if (key) contributorCounts[key] = (contributorCounts[key] || 0) + 1;
                });
              });
              setTopContributors(Object.entries(contributorCounts).map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count));
              return;
           }
        }

        // Fetch dashboard data generated by the Google Sheets scraper endpoint
        const sheetsRes = await apiFetch(`/api/sheets-dashboard`);
        if (!sheetsRes.ok) throw new Error('Failed to fetch sheets data');
        const sheetsData = await sheetsRes.json();

        // 1. Process data from the parsed sheets for the dashboard metrics
        let allStudents = [];
        let totalCertificates = 0;
        let studyPaths = 0;

        // Keys of sheets containing students
        const studentSheets = ['Technical Team', 'CVE Hunt Team', 'Escape Room Team', 'Cyber-AR&VR', 'Internship/Placed', 'Future Participations', 'Project'];
        const seenNames = new Set();

        Object.keys(sheetsData).forEach(sheetName => {
          // Flatten student lists
          if (studentSheets.includes(sheetName)) {
            sheetsData[sheetName].forEach(row => {
               const stName = row['NAME'] || row['NAME '] || row['STUDENT LEARNER'] || row['LEADING BY'];
               if (stName) {
                 const normName = stName.toLowerCase().replace(/[\s\.]/g, '').replace('auswath', 'asuwath');
                 if (!seenNames.has(normName)) {
                   seenNames.add(normName);
                   allStudents.push({
                     id: Math.random().toString(36).substring(2, 9),
                     displayName: stName.trim(),
                     name: stName.trim(),
                     teamName: row['TEAM NAME'] || sheetName,
                     deptYear: row['DEPT - YEAR'] || 'Unknown',
                     level: sheetName === 'Technical Team' ? 'Hard' : (sheetName === 'Internship/Placed' ? 'Expert' : 'Medium'),
                     inferredLevel: sheetName === 'Technical Team' ? 'Hard' : (sheetName === 'Internship/Placed' ? 'Expert' : 'Medium'),
                     completedPaths: sheetName === 'Internship/Placed' ? 2 : 0,
                   });
                 }
               }
            });
          }

          // Count certificates / achievements
          if (sheetName === 'Achievements') {
            totalCertificates += sheetsData[sheetName].length;
          }
           // Count active study paths as number of current projects/tasks from the "Project" tab
           if (sheetName === 'Project') {
             studyPaths += sheetsData[sheetName].length;
           }
        });

        // Use a Sets Map to deduce unique students by name
        const uniqueStudentsMap = new Map();
        allStudents.forEach(s => {
          if (!uniqueStudentsMap.has(s.displayName)) uniqueStudentsMap.set(s.displayName, s);
        });
        const uniqueStudents = Array.from(uniqueStudentsMap.values());

        // Update the basic state tracking totals
        setSummary({
          totalStudents: uniqueStudents.length,
          totalCertificates: totalCertificates,
          activeStudyPaths: studyPaths,
          totalAchievements: totalCertificates,
          totalCves: 16,
          totalTeams: 0
        });

        // 2. Set the direct operative listing in dashboard UI
        setStudents(uniqueStudents);
        setRecentAchievements(sheetsData['Achievements']?.slice(0, 5) || []);
        setRecentCves(sheetsData['CVEs']?.slice(0, 5) || []);
        setProjects([]);
        setTeams([]);
        setTopContributors([]);

      } catch (err) {
        console.error(err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [useDatabase]);

  const rangeProject = projects.find(project => project.title === 'Incognitrix Range');
  const portfolioProject = projects.find(project => project.title === 'Incognitrix Portfolio');
  const latestAchievement = recentAchievements[0];
  const leadFinder = topContributors[0];
  const projectReadiness = projects.length ? Math.round((projects.filter(project => String(project.status || '').toLowerCase().includes('ongoing') || String(project.status || '').toLowerCase().includes('active')).length / projects.length) * 100) : 0;

  if (loading) {
    return (
      <div className="pt-12 pb-12 px-6 lg:px-12 max-w-7xl mx-auto w-full text-center">
        <span className="material-symbols-outlined text-primary text-6xl animate-spin">data_usage</span>
        <h2 className="font-headline text-2xl font-bold tracking-tight text-on-surface mt-4">INITIALIZING TELEMETRY...</h2>
      </div>
    );
  }

  if (error) {
    return (
      <div className="pt-12 pb-12 px-6 lg:px-12 max-w-7xl mx-auto w-full text-center">
        <span className="material-symbols-outlined text-error text-6xl">error</span>
        <h2 className="font-headline text-2xl font-bold tracking-tight text-error mt-4">TELEMETRY FAILURE</h2>
        <p className="font-mono text-sm text-outline mt-2">{error}</p>
      </div>
    );
  }

  return (
    <div className="pt-12 pb-12 px-6 lg:px-12 max-w-7xl mx-auto w-full flex flex-col gap-8 text-on-surface animate-fade-slide">
      <header className="mb-4 bg-surface-container-low border ghost-border rounded p-6 md:p-8 relative overflow-hidden">
        <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-error via-primary to-emerald-400 opacity-80"></div>
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-end">
          <div className="lg:col-span-7">
            <div className="font-mono text-[10px] uppercase tracking-[0.35em] text-primary-container mb-3">Incognitrix Lab Telemetry</div>
            <h1 className="font-headline text-4xl md:text-6xl font-bold tracking-tight mb-3 uppercase text-primary">Command Dashboard</h1>
            <p className="text-on-surface-variant max-w-3xl text-sm md:text-base opacity-90 leading-relaxed font-mono">
              Live operational view across products, teams, CVE research, achievements, and personnel activity.
            </p>
          </div>
          <div className="lg:col-span-5 grid grid-cols-3 gap-3">
            <div className="bg-background/60 border border-outline/20 rounded p-4">
              <div className="font-mono text-[10px] text-outline uppercase mb-1">Readiness</div>
              <div className="font-headline text-2xl text-emerald-400 font-bold">{projectReadiness}%</div>
            </div>
            <div className="bg-background/60 border border-outline/20 rounded p-4">
              <div className="font-mono text-[10px] text-outline uppercase mb-1">Lead CVE</div>
              <div className="font-headline text-lg text-primary font-bold truncate">{leadFinder?.name || 'N/A'}</div>
            </div>
            <div className="bg-background/60 border border-outline/20 rounded p-4">
              <div className="font-mono text-[10px] text-outline uppercase mb-1">Latest</div>
              <div className="font-headline text-lg text-secondary font-bold truncate">{latestAchievement?.title || 'N/A'}</div>
            </div>
          </div>
        </div>
      </header>

      {/* Top Metrics Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-surface-container-low p-6 rounded border ghost-border relative overflow-hidden flex flex-col items-center text-center">
          <div className="absolute top-0 w-full h-1 bg-gradient-to-r from-transparent via-primary-container to-transparent opacity-50"></div>
          <span className="material-symbols-outlined text-primary-container text-4xl mb-2">groups</span>
          <h3 className="font-mono text-xs uppercase tracking-widest text-outline mb-1">Total Operatives</h3>
          <span className="font-headline text-5xl font-bold text-on-surface">
            {summary?.totalStudents || students.length || 0}
          </span>
        </div>
        
        <div className="bg-surface-container-low p-6 rounded border ghost-border relative overflow-hidden flex flex-col items-center text-center">
          <div className="absolute top-0 w-full h-1 bg-gradient-to-r from-transparent via-emerald-400 to-transparent opacity-50"></div>
          <span className="material-symbols-outlined text-emerald-400 text-4xl mb-2">security</span>
          <h3 className="font-mono text-xs uppercase tracking-widest text-outline mb-1">Total CVEs</h3>
          <span className="font-headline text-5xl font-bold text-on-surface">
            {summary?.totalCves || 0}
          </span>
        </div>

        <div className="bg-surface-container-low p-6 rounded border ghost-border relative overflow-hidden flex flex-col items-center text-center">
          <div className="absolute top-0 w-full h-1 bg-gradient-to-r from-transparent via-blue-500 to-transparent opacity-50"></div>
          <span className="material-symbols-outlined text-blue-500 text-4xl mb-2">hub</span>
          <h3 className="font-mono text-xs uppercase tracking-widest text-outline mb-1">Total Products</h3>
          <span className="font-headline text-5xl font-bold text-on-surface">
            {summary?.activeStudyPaths || 0}
          </span>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mt-0">
        <div className="bg-surface-container-low p-6 rounded border ghost-border relative overflow-hidden flex flex-col items-center text-center col-span-1 md:col-start-2 md:col-span-2">
          <div className="absolute top-0 w-full h-1 bg-gradient-to-r from-transparent via-purple-500 to-transparent opacity-50"></div>
          <span className="material-symbols-outlined text-purple-500 text-4xl mb-2">military_tech</span>
          <h3 className="font-mono text-xs uppercase tracking-widest text-outline mb-1">Total Achievements</h3>
          <span className="font-headline text-5xl font-bold text-on-surface">
            {summary?.totalAchievements ?? Math.floor((summary?.totalCertificates || 0) * 1.5)}
          </span>
        </div>
      </div>
      <div className="grid grid-cols-1 xl:grid-cols-12 gap-6">
        <section className="xl:col-span-7 bg-surface-container-low p-6 rounded border ghost-border relative overflow-hidden">
          <div className="absolute top-0 right-0 text-9xl material-symbols-outlined text-primary/5 select-none pointer-events-none">radar</div>
          <h3 className="font-headline text-2xl font-bold text-primary mb-4 flex items-center gap-2">
            <span className="material-symbols-outlined text-primary-container">tactic</span>
            Range Operations
          </h3>
          <p className="font-mono text-sm text-on-surface-variant leading-relaxed line-clamp-5">
            {rangeProject?.description || 'Incognitrix Range operations are awaiting database telemetry.'}
          </p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-6">
            {['Advisor Simulation', 'Pro Labs', 'Boot2Root', 'CVE Simulations'].map(label => (
              <div key={label} className="bg-background/60 border border-outline/20 rounded p-3">
                <div className="font-mono text-[10px] text-outline uppercase">{label}</div>
                <div className="mt-2 h-1 bg-primary rounded-full"></div>
              </div>
            ))}
          </div>
        </section>

        <section className="xl:col-span-5 bg-surface-container-low p-6 rounded border ghost-border">
          <h3 className="font-headline text-2xl font-bold text-primary mb-4 flex items-center gap-2">
            <span className="material-symbols-outlined text-primary-container">verified_user</span>
            Research Signal
          </h3>
          <div className="space-y-4">
            {recentAchievements.slice(0, 3).map(achievement => (
              <div key={achievement.id} className="border-l-2 border-primary pl-4">
                <div className="font-headline text-sm font-bold text-on-surface">{achievement.title}</div>
                <div className="font-mono text-xs text-outline line-clamp-2">{achievement.description}</div>
              </div>
            ))}
          </div>
        </section>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-surface-container-low p-6 rounded border ghost-border">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-headline text-xl font-bold text-primary flex items-center gap-2">
              <span className="material-symbols-outlined text-primary-container">account_tree</span>
              Product Snapshot
            </h3>
            <span className="font-mono text-xs text-outline">{projects.length} Active</span>
          </div>
          <div className="space-y-3">
            {projects.slice(0, 5).map(project => {
              let operatives = [];
              try { operatives = typeof project.operatives === 'string' ? JSON.parse(project.operatives) : project.operatives || []; } catch(e){}
              return (
                <div key={project.id} className="border-b border-outline/10 last:border-b-0 pb-3 last:pb-0">
                  <div className="font-headline text-sm font-bold text-on-surface">{project.title}</div>
                  <div className="font-mono text-xs text-outline">{project.team || 'Incognitrix Lab'} / {operatives[0]?.name || 'Team-led'}</div>
                </div>
              );
            })}
          </div>
        </div>

        <div className="bg-surface-container-low p-6 rounded border ghost-border">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-headline text-xl font-bold text-primary flex items-center gap-2">
              <span className="material-symbols-outlined text-primary-container">groups</span>
              Team Coverage
            </h3>
            <span className="font-mono text-xs text-outline">{summary?.totalTeams || teams.length} Teams</span>
          </div>
          <div className="flex flex-wrap gap-2">
            {teams.slice(0, 12).map(team => (
              <span key={team.id} className={`font-mono text-[10px] uppercase px-2 py-1 rounded border ${team.name === 'Red Team' ? 'text-error border-error/30 bg-error/10' : 'text-on-surface-variant border-outline/20 bg-surface-container-high'}`}>
                {team.name}
              </span>
            ))}
          </div>
        </div>

        <div className="bg-surface-container-low p-6 rounded border ghost-border">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-headline text-xl font-bold text-primary flex items-center gap-2">
              <span className="material-symbols-outlined text-primary-container">workspace_premium</span>
              CVE Finders
            </h3>
            <span className="font-mono text-xs text-outline">{summary?.totalCves || 0} CVEs</span>
          </div>
          <div className="space-y-3">
            {topContributors.slice(0, 4).map(contributor => (
              <div key={contributor.name} className="flex items-center justify-between border-b border-outline/10 last:border-b-0 pb-2 last:pb-0">
                <span className="font-headline text-sm font-bold text-on-surface">{contributor.name}</span>
                <span className="font-mono text-xs text-primary">{contributor.count}</span>
              </div>
            ))}
            {topContributors.length === 0 && <div className="font-mono text-sm text-outline">No CVE contributor data.</div>}
          </div>
        </div>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 bg-surface-container-low p-6 rounded border ghost-border">
          <h3 className="font-headline text-xl font-bold text-primary mb-4 flex items-center gap-2">
            <span className="material-symbols-outlined text-primary-container">lan</span>
            Product Leads Matrix
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {projects.map(project => {
              let operatives = [];
              try { operatives = typeof project.operatives === 'string' ? JSON.parse(project.operatives) : project.operatives || []; } catch(e){}
              return (
                <div key={project.id} className="bg-background/50 border border-outline/15 rounded p-4">
                  <div className="font-headline text-base font-bold text-on-surface">{project.title}</div>
                  <div className="font-mono text-xs text-primary mt-1">{operatives[0]?.name || 'Team-led'}{operatives[0]?.role ? ` / ${operatives[0].role}` : ''}</div>
                  <div className="font-mono text-[10px] text-outline uppercase mt-3">{project.team || project.priority || 'Incognitrix Lab'}</div>
                </div>
              );
            })}
          </div>
        </div>

        <div className="bg-surface-container-low p-6 rounded border ghost-border">
          <h3 className="font-headline text-xl font-bold text-primary mb-4 flex items-center gap-2">
            <span className="material-symbols-outlined text-primary-container">webhook</span>
            Portal Status
          </h3>
          <div className="font-mono text-sm text-on-surface-variant leading-relaxed">
            {portfolioProject?.shortDesc || 'Portfolio telemetry is active.'}
          </div>
          <div className="mt-6 grid grid-cols-2 gap-3">
            <div className="bg-background/60 border border-outline/20 rounded p-3">
              <div className="text-[10px] text-outline uppercase font-mono">Source</div>
              <div className="text-sm text-primary font-headline font-bold">{useDatabase ? 'DB' : 'Sheet'}</div>
            </div>
            <div className="bg-background/60 border border-outline/20 rounded p-3">
              <div className="text-[10px] text-outline uppercase font-mono">Sync</div>
              <div className="text-sm text-emerald-400 font-headline font-bold">Live</div>
            </div>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-surface-container-low p-6 rounded border ghost-border">
          <h3 className="font-headline text-xl font-bold text-primary mb-4 flex items-center gap-2">
            <span className="material-symbols-outlined text-primary-container">military_tech</span>
            Recent Achievements
          </h3>
          <div className="flex flex-col gap-3">
            {recentAchievements.length > 0 ? recentAchievements.map((achievement, index) => (
              <div key={achievement.id || index} className="border-b border-outline/10 last:border-b-0 pb-3 last:pb-0">
                <div className="font-headline text-sm font-bold text-on-surface">{achievement.title || achievement.NAME || 'Achievement'}</div>
                <div className="font-mono text-xs text-outline line-clamp-2">{achievement.description || achievement.DETAILS || achievement.future_scope || 'Milestone recorded in the lab database.'}</div>
              </div>
            )) : (
              <div className="font-mono text-sm text-outline">No achievements recorded yet.</div>
            )}
          </div>
        </div>

        <div className="bg-surface-container-low p-6 rounded border ghost-border">
          <h3 className="font-headline text-xl font-bold text-primary mb-4 flex items-center gap-2">
            <span className="material-symbols-outlined text-primary-container">security</span>
            CVE Intel
          </h3>
          <div className="flex flex-col gap-3">
            {recentCves.length > 0 ? recentCves.map((cve, index) => (
              <div key={cve.id || index} className="border-b border-outline/10 last:border-b-0 pb-3 last:pb-0">
                <div className="font-headline text-sm font-bold text-error">{cve.cve_number || cve.CVE || 'CVE Record'}</div>
                <div className="font-mono text-xs text-outline line-clamp-2">{cve.details || cve.DETAILS || 'Vulnerability details stored in database.'}</div>
              </div>
            )) : (
              <div className="font-mono text-sm text-outline">No CVE records in the database.</div>
            )}
          </div>
        </div>
      </div>
      {/* Detailed Table */}
      <div className="bg-surface-container-low p-6 rounded flex flex-col gap-4 border ghost-border">
        <h3 className="font-headline text-xl font-bold text-primary flex items-center gap-2 mb-2">
          <span className="material-symbols-outlined text-primary-container">table_view</span>
          Operative Ledger
        </h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm font-mono whitespace-nowrap">
            <thead className="text-outline uppercase tracking-wider border-b border-outline/20">
              <tr>
                <th className="px-4 py-3">ID / Display Name</th>
                <th className="px-4 py-3">Username</th>
                <th className="px-4 py-3">Current Level</th>
                <th className="px-4 py-3">Completed Paths</th>
                <th className="px-4 py-3">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-outline/10 text-on-surface-variant">
              {students && students.map((s) => (
                <tr key={s.id} className="hover:bg-surface-bright transition-colors group">
                  <td className="px-4 py-3 text-on-surface font-headline font-bold">
                    {s.displayName || `Op-${s.id}`}
                  </td>
                  <td className="px-4 py-3">{s.username || s.name || 'UNKNOWN'}</td>
                  <td className="px-4 py-3">
                    <span className="bg-primary/10 text-primary border border-primary/20 px-2 py-0.5 rounded text-[10px] uppercase">
                      LEVEL {s.level || 0}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-emerald-400">
                    {s.completedPaths || 0} Paths
                  </td>
                  <td className="px-4 py-3 group-hover:text-primary transition-colors">
                    ACTIVE
                  </td>
                </tr>
              ))}
              {(!students || students.length === 0) && (
                <tr>
                  <td colSpan="5" className="px-4 py-8 text-center text-outline">
                    No operating personnel data retrieved.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export default Dashboard;
